### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by 3dln** [saylar89/Realestate#6]
Please add a layout component and insert header and footer.
Inside the header we need a navigation menu

**Comment by saylar89** [comment]
Header and Footer with navigation menu created successfully.

**Comment by 3dln** [comment]
Please use Next.js <Link> component to prevent page refreshing in all links

**Comment by 3dln** [comment]
> 
> 
> Header and Footer with navigation menu created successfully.

Please use Next.js Link component to prevent page refreshing in all links

**Comment by 3dln** [comment]
It's much better if footer always sticks to the bottom of the page

**Comment by 3dln** [comment]
create empty pages for all the links in the header

**Comment by 3dln** [comment]
It's a good practice to make titles always bolder and bigger than list items (Footer items in this case)
Also please left align all the lists and titles in the footer

**Comment by saylar89** [comment]
Done

**Comment by 3dln** [comment]
We still don't have empty pages for other links (all links must have a corresponding empty page)

**Comment by saylar89** [comment]
Empty pages created.
